# Generated by Django 6.0.1 on 2026-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('so_reference', models.CharField(max_length=100)),
                ('dispatched_date', models.DateField()),
                ('ref_document', models.FileField(blank=True, null=True, upload_to='outbound_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
