# Generated by Django 6.0.1 on 2026-01-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundtransaction',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outboundtransaction',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
