# Generated by Django 6.0.1 on 2026-01-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], default='ADMIN', max_length=20),
        ),
    ]
